### ISSUE TITLE
`report_interval` missing in `model_args`?

### ISSUE THREAD

**Issue by Querela** [jwieting/paraphrastic-representations-at-scale#4]
I just tried out the example calls and got an error:

```bash
python -u score_sentence_pairs.py --sentence-pair-file paraphrase-at-scale/example-sentences-pairs.txt --load-file paraphrase-at-scale/model.para.lc.100.pt  --sp-model paraphrase-at-scale/paranmt.model --gpu 0
```

```python
Traceback (most recent call last):
  File "score_sentence_pairs.py", line 88, in <module>
    model, _ = load_model(None, args)
  File "/content/paraphrastic-representations-at-scale/models.py", line 35, in load_model
    model = Averaging(data, model_args, vocab, vocab_fr)
  File "/content/paraphrastic-representations-at-scale/models.py", line 205, in __init__
    super(Averaging, self).__init__(data, args, vocab, vocab_fr)
  File "/content/paraphrastic-representations-at-scale/models.py", line 52, in __init__
    self.report_interval = args.report_interval
AttributeError: 'Namespace' object has no attribute 'report_interval'
```

https://github.com/jwieting/paraphrastic-representations-at-scale/blob/1e49a4a7de1619a189e63cce7cd4f3138b53e7a8/models.py#L51-L52

Replacing `args.report_interval` with `args.save_interval` let's me run the example but is no real solution...

It seems like the code was maybe later changed but the saved models do not contain the changes:  
`model = torch.load(args.load_file)` &rarr; `model_args = model['args']` &rarr; `model_args.report_interval` ?

**Comment by tanmaylaud** [comment]
I am getting the same error

**Comment by jwcmu** [comment]
Thank you for reporting this issue! It should be fixed now.

**Comment by jwieting** [comment]
Thank you for reporting this issue! It should be fixed now.
